# This Makefile is generated by omake: https://github.com/ouonline/omake.git

AR := ar
CC := gcc

ifeq ($(debug), y)
	CFLAGS := -g
else
	CFLAGS := -O2 -DNDEBUG
endif
CFLAGS := $(CFLAGS) -Wall -Werror -Wextra -fPIC

TARGET := libhttpkit.a libhttpkit.so

.PHONY: all clean

all: $(TARGET)

httpkit_OBJS := ./http_response.c.httpkit.o ./http_header.c.httpkit.o ./http_request.c.httpkit.o ./http_utils.c.httpkit.o

httpkit_INCLUDE := -I..

httpkit_LIBS := ../utils/libutils.a

./http_response.c.httpkit.o: ./http_response.c
	$(CC) $(CFLAGS) $(httpkit_INCLUDE) -c $< -o $@

./http_header.c.httpkit.o: ./http_header.c
	$(CC) $(CFLAGS) $(httpkit_INCLUDE) -c $< -o $@

./http_request.c.httpkit.o: ./http_request.c
	$(CC) $(CFLAGS) $(httpkit_INCLUDE) -c $< -o $@

./http_utils.c.httpkit.o: ./http_utils.c
	$(CC) $(CFLAGS) $(httpkit_INCLUDE) -c $< -o $@

.PHONY: httpkit_pre_process

$(httpkit_OBJS): | httpkit_pre_process

httpkit_pre_process:
	$(MAKE) debug=$(debug) -C ../utils

libhttpkit.a: $(httpkit_OBJS)
	$(AR) rc $@ $^

libhttpkit.so: $(httpkit_OBJS)
	$(CC) -shared -o $@ $^ $(httpkit_LIBS)

clean:
	rm -f $(TARGET) $(httpkit_OBJS)
